### PR TITLE
Fixed two typos in ex3-5.html

### PR DESCRIPTION
**Pull request by siFeiden**
(l. 48) .. take a different approach of we want .. -> .. if we want ..
(l. 51) impliment -> implement

### CODE REVIEW

**Comment by mightybyte** [comment]
Thanks! Could you make that change to hakyll/pages/ex3-5.md instead? The html files are generated from the markdown files. If you don't want to take the time, I can do it myself, but I wanted you to have the chance to have the contribution show up with proper credit in the git history.

**Comment by siFeiden** [comment]
Yes sure, I'll update it to the correct file.
Thanks for reminding me!

**Comment by mightybyte** [comment]
Oops, there's a merge conflict now.  Could you resolve it?  Sorry this fix has been so much trouble.

**Comment by siFeiden** [comment]
Done.

**Comment by mightybyte** [comment]
Grrr, the fixes reverted some of the intervening work.  Sorry for all the trouble.  Since it was a one character typo I decided to just fix it myself.  I referenced you in the commit.

**Pull request closed without merging**
